# Generated by Django 2.1.7 on 2019-03-16 11:55

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('prescription', models.CharField(default='WITAMINA C', max_length=180)),
                ('exp_date', models.DateField(verbose_name=django.forms.widgets.SelectDateWidget)),
            ],
        ),
    ]
